name: ff_annotation_route
description: Provide a route generator to create route map quickly by annotations.
version: 4.0.0
homepage: https://github.com/fluttercandies/ff_annotation_route

environment:
  sdk: '>=2.6.0 <3.0.0'
dependencies:
  analyzer: ^0.40.2
  dart_style: ^1.3.7
  io: ^0.3.4
  meta: ^1.2.3
  path: ^1.7.0
  yaml: ^2.2.1

executables:
  ff_route: main

 # pub global activate --source path ./
 # pub global activate ff_annotation_route