name: ff_annotation_route
description: Provide a route generator to create route map quickly by annotations.
version: 3.1.0
homepage: https://github.com/fluttercandies/ff_annotation_route

environment:
  sdk: '>=2.2.0 <3.0.0'
dependencies:
  analyzer: ^0.39.2+1
  meta: ^1.1.8
  path: ^1.0.0
  yaml: ^2.0.0
  io: ^0.3.3
  dart_style: ^1.3.6

executables:
  ff_route: main

 # pub global activate --source path ./ 